import tour1 from '../../Assets/tour-1.jpg';
import tour2 from '../../Assets/tour-2.jpg';
import tour3 from '../../Assets/tour-3.jpg';
import tour4 from '../../Assets/tour-4.jpg';
import tour5 from '../../Assets/tour-5.jpg';
import tour6 from '../../Assets/tour-6.jpg';
const tours = [
	{
		id: 1,
		img: tour1,
		rate: 4.5,
		title: 'Krabi, Thailand',
		price: 20,
		text:
			'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla sem ex, lobortis vitae condimentum quis, pharetra at nisl. Quisque accumsan risus eu auctor pellentesque. Donec a lectus ullamcorper, tempor dolor non, tristique odio. Quisque velit nisl, malesuada eget porttitor porttitor, scelerisque ut nulla. Phasellus tincidunt justo vel nibh tempus, eu condimentum dui consequat.Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla sem ex, lobortis vitae condimentum quis, pharetra at nisl. Quisque accumsan risus eu auctor pellentesque. Donec a lectus ullamcorper, tempor dolor non, tristique odio. Quisque velit nisl, malesuada eget porttitor porttitor, scelerisque ut nulla. Phasellus tincidunt justo vel nibh tempus, eu condimentum dui consequat.Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla sem ex, lobortis vitae condimentum quis, pharetra at nisl. Quisque accumsan risus eu auctor pellentesque. Donec a lectus ullamcorper, tempor dolor non, tristique odio. Quisque velit nisl, malesuada eget porttitor porttitor, scelerisque ut nulla. Phasellus tincidunt justo vel nibh tempus, eu condimentum dui consequat.Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla sem ex, lobortis vitae condimentum quis, pharetra at nisl. Quisque accumsan risus eu auctor pellentesque. Donec a lectus ullamcorper, tempor dolor non, tristique odio. Quisque velit nisl, malesuada eget porttitor porttitor, scelerisque ut nulla. Phasellus tincidunt justo vel nibh tempus, eu condimentum dui consequat.Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla sem ex, lobortis vitae condimentum quis, pharetra at nisl. Quisque accumsan risus eu auctor pellentesque. Donec a lectus ullamcorper, tempor dolor non, tristique odio. Quisque velit nisl, malesuada eget porttitor porttitor, scelerisque ut nulla. Phasellus tincidunt justo vel nibh tempus, eu condimentum dui consequat.Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla sem ex, lobortis vitae condimentum quis, pharetra at nisl. Quisque accumsan risus eu auctor pellentesque. Donec a lectus ullamcorper, tempor dolor non, tristique odio. Quisque velit nisl, malesuada eget porttitor porttitor, scelerisque ut nulla. Phasellus tincidunt justo vel nibh tempus, eu condimentum dui consequat.'
	},
	{
		id: 2,
		img: tour2,
		rate: 4,
		title: 'Multnomah Falls, United State',
		price: 80,
		text:
			'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla sem ex, lobortis vitae condimentum quis, pharetra at nisl. Quisque accumsan risus eu auctor pellentesque. Donec a lectus ullamcorper, tempor dolor non, tristique odio. Quisque velit nisl, malesuada eget porttitor porttitor, scelerisque ut nulla. Phasellus tincidunt justo vel nibh tempus, eu condimentum dui consequat.Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla sem ex, lobortis vitae condimentum quis, pharetra at nisl. Quisque accumsan risus eu auctor pellentesque. Donec a lectus ullamcorper, tempor dolor non, tristique odio. Quisque velit nisl, malesuada eget porttitor porttitor, scelerisque ut nulla. Phasellus tincidunt justo vel nibh tempus, eu condimentum dui consequat.Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla sem ex, lobortis vitae condimentum quis, pharetra at nisl. Quisque accumsan risus eu auctor pellentesque. Donec a lectus ullamcorper, tempor dolor non, tristique odio. Quisque velit nisl, malesuada eget porttitor porttitor, scelerisque ut nulla. Phasellus tincidunt justo vel nibh tempus, eu condimentum dui consequat.Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla sem ex, lobortis vitae condimentum quis, pharetra at nisl. Quisque accumsan risus eu auctor pellentesque. Donec a lectus ullamcorper, tempor dolor non, tristique odio. Quisque velit nisl, malesuada eget porttitor porttitor, scelerisque ut nulla. Phasellus tincidunt justo vel nibh tempus, eu condimentum dui consequat.Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla sem ex, lobortis vitae condimentum quis, pharetra at nisl. Quisque accumsan risus eu auctor pellentesque. Donec a lectus ullamcorper, tempor dolor non, tristique odio. Quisque velit nisl, malesuada eget porttitor porttitor, scelerisque ut nulla. Phasellus tincidunt justo vel nibh tempus, eu condimentum dui consequat.Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla sem ex, lobortis vitae condimentum quis, pharetra at nisl. Quisque accumsan risus eu auctor pellentesque. Donec a lectus ullamcorper, tempor dolor non, tristique odio. Quisque velit nisl, malesuada eget porttitor porttitor, scelerisque ut nulla. Phasellus tincidunt justo vel nibh tempus, eu condimentum dui consequat.'
	},
	{
		id: 3,
		img: tour3,
		rate: 4.3,
		title: 'Chitwan National Park, Nepal',
		price: 120,
		text:
			'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla sem ex, lobortis vitae condimentum quis, pharetra at nisl. Quisque accumsan risus eu auctor pellentesque. Donec a lectus ullamcorper, tempor dolor non, tristique odio. Quisque velit nisl, malesuada eget porttitor porttitor, scelerisque ut nulla. Phasellus tincidunt justo vel nibh tempus, eu condimentum dui consequat.Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla sem ex, lobortis vitae condimentum quis, pharetra at nisl. Quisque accumsan risus eu auctor pellentesque. Donec a lectus ullamcorper, tempor dolor non, tristique odio. Quisque velit nisl, malesuada eget porttitor porttitor, scelerisque ut nulla. Phasellus tincidunt justo vel nibh tempus, eu condimentum dui consequat.Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla sem ex, lobortis vitae condimentum quis, pharetra at nisl. Quisque accumsan risus eu auctor pellentesque. Donec a lectus ullamcorper, tempor dolor non, tristique odio. Quisque velit nisl, malesuada eget porttitor porttitor, scelerisque ut nulla. Phasellus tincidunt justo vel nibh tempus, eu condimentum dui consequat.Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla sem ex, lobortis vitae condimentum quis, pharetra at nisl. Quisque accumsan risus eu auctor pellentesque. Donec a lectus ullamcorper, tempor dolor non, tristique odio. Quisque velit nisl, malesuada eget porttitor porttitor, scelerisque ut nulla. Phasellus tincidunt justo vel nibh tempus, eu condimentum dui consequat.Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla sem ex, lobortis vitae condimentum quis, pharetra at nisl. Quisque accumsan risus eu auctor pellentesque. Donec a lectus ullamcorper, tempor dolor non, tristique odio. Quisque velit nisl, malesuada eget porttitor porttitor, scelerisque ut nulla. Phasellus tincidunt justo vel nibh tempus, eu condimentum dui consequat.Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla sem ex, lobortis vitae condimentum quis, pharetra at nisl. Quisque accumsan risus eu auctor pellentesque. Donec a lectus ullamcorper, tempor dolor non, tristique odio. Quisque velit nisl, malesuada eget porttitor porttitor, scelerisque ut nulla. Phasellus tincidunt justo vel nibh tempus, eu condimentum dui consequat.'
	},
	{
		id: 4,
		img: tour4,
		rate: 4.1,
		title: 'Mont Blanc, France',
		price: 200,
		text:
			'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla sem ex, lobortis vitae condimentum quis, pharetra at nisl. Quisque accumsan risus eu auctor pellentesque. Donec a lectus ullamcorper, tempor dolor non, tristique odio. Quisque velit nisl, malesuada eget porttitor porttitor, scelerisque ut nulla. Phasellus tincidunt justo vel nibh tempus, eu condimentum dui consequat.Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla sem ex, lobortis vitae condimentum quis, pharetra at nisl. Quisque accumsan risus eu auctor pellentesque. Donec a lectus ullamcorper, tempor dolor non, tristique odio. Quisque velit nisl, malesuada eget porttitor porttitor, scelerisque ut nulla. Phasellus tincidunt justo vel nibh tempus, eu condimentum dui consequat.Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla sem ex, lobortis vitae condimentum quis, pharetra at nisl. Quisque accumsan risus eu auctor pellentesque. Donec a lectus ullamcorper, tempor dolor non, tristique odio. Quisque velit nisl, malesuada eget porttitor porttitor, scelerisque ut nulla. Phasellus tincidunt justo vel nibh tempus, eu condimentum dui consequat.Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla sem ex, lobortis vitae condimentum quis, pharetra at nisl. Quisque accumsan risus eu auctor pellentesque. Donec a lectus ullamcorper, tempor dolor non, tristique odio. Quisque velit nisl, malesuada eget porttitor porttitor, scelerisque ut nulla. Phasellus tincidunt justo vel nibh tempus, eu condimentum dui consequat.Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla sem ex, lobortis vitae condimentum quis, pharetra at nisl. Quisque accumsan risus eu auctor pellentesque. Donec a lectus ullamcorper, tempor dolor non, tristique odio. Quisque velit nisl, malesuada eget porttitor porttitor, scelerisque ut nulla. Phasellus tincidunt justo vel nibh tempus, eu condimentum dui consequat.Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla sem ex, lobortis vitae condimentum quis, pharetra at nisl. Quisque accumsan risus eu auctor pellentesque. Donec a lectus ullamcorper, tempor dolor non, tristique odio. Quisque velit nisl, malesuada eget porttitor porttitor, scelerisque ut nulla. Phasellus tincidunt justo vel nibh tempus, eu condimentum dui consequat.'
	},
	{
		id: 5,
		img: tour5,
		rate: 4.2,
		title: 'Erg Chebbi, Morocco',
		price: 60,
		text:
			'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla sem ex, lobortis vitae condimentum quis, pharetra at nisl. Quisque accumsan risus eu auctor pellentesque. Donec a lectus ullamcorper, tempor dolor non, tristique odio. Quisque velit nisl, malesuada eget porttitor porttitor, scelerisque ut nulla. Phasellus tincidunt justo vel nibh tempus, eu condimentum dui consequat.Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla sem ex, lobortis vitae condimentum quis, pharetra at nisl. Quisque accumsan risus eu auctor pellentesque. Donec a lectus ullamcorper, tempor dolor non, tristique odio. Quisque velit nisl, malesuada eget porttitor porttitor, scelerisque ut nulla. Phasellus tincidunt justo vel nibh tempus, eu condimentum dui consequat.Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla sem ex, lobortis vitae condimentum quis, pharetra at nisl. Quisque accumsan risus eu auctor pellentesque. Donec a lectus ullamcorper, tempor dolor non, tristique odio. Quisque velit nisl, malesuada eget porttitor porttitor, scelerisque ut nulla. Phasellus tincidunt justo vel nibh tempus, eu condimentum dui consequat.Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla sem ex, lobortis vitae condimentum quis, pharetra at nisl. Quisque accumsan risus eu auctor pellentesque. Donec a lectus ullamcorper, tempor dolor non, tristique odio. Quisque velit nisl, malesuada eget porttitor porttitor, scelerisque ut nulla. Phasellus tincidunt justo vel nibh tempus, eu condimentum dui consequat.Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla sem ex, lobortis vitae condimentum quis, pharetra at nisl. Quisque accumsan risus eu auctor pellentesque. Donec a lectus ullamcorper, tempor dolor non, tristique odio. Quisque velit nisl, malesuada eget porttitor porttitor, scelerisque ut nulla. Phasellus tincidunt justo vel nibh tempus, eu condimentum dui consequat.Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla sem ex, lobortis vitae condimentum quis, pharetra at nisl. Quisque accumsan risus eu auctor pellentesque. Donec a lectus ullamcorper, tempor dolor non, tristique odio. Quisque velit nisl, malesuada eget porttitor porttitor, scelerisque ut nulla. Phasellus tincidunt justo vel nibh tempus, eu condimentum dui consequat.'
	},
	{
		id: 6,
		img: tour6,
		rate: 4.4,
		title: 'Adjara, Georgia',
		price: 78,
		text:
			'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla sem ex, lobortis vitae condimentum quis, pharetra at nisl. Quisque accumsan risus eu auctor pellentesque. Donec a lectus ullamcorper, tempor dolor non, tristique odio. Quisque velit nisl, malesuada eget porttitor porttitor, scelerisque ut nulla. Phasellus tincidunt justo vel nibh tempus, eu condimentum dui consequatLorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla sem ex, lobortis vitae condimentum quis, pharetra at nisl. Quisque accumsan risus eu auctor pellentesque. Donec a lectus ullamcorper, tempor dolor non, tristique odio. Quisque velit nisl, malesuada eget porttitor porttitor, scelerisque ut nulla. Phasellus tincidunt justo vel nibh tempus, eu condimentum dui consequat.Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla sem ex, lobortis vitae condimentum quis, pharetra at nisl. Quisque accumsan risus eu auctor pellentesque. Donec a lectus ullamcorper, tempor dolor non, tristique odio. Quisque velit nisl, malesuada eget porttitor porttitor, scelerisque ut nulla. Phasellus tincidunt justo vel nibh tempus, eu condimentum dui consequat.Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla sem ex, lobortis vitae condimentum quis, pharetra at nisl. Quisque accumsan risus eu auctor pellentesque. Donec a lectus ullamcorper, tempor dolor non, tristique odio. Quisque velit nisl, malesuada eget porttitor porttitor, scelerisque ut nulla. Phasellus tincidunt justo vel nibh tempus, eu condimentum dui consequat.Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla sem ex, lobortis vitae condimentum quis, pharetra at nisl. Quisque accumsan risus eu auctor pellentesque. Donec a lectus ullamcorper, tempor dolor non, tristique odio. Quisque velit nisl, malesuada eget porttitor porttitor, scelerisque ut nulla. Phasellus tincidunt justo vel nibh tempus, eu condimentum dui consequat.Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla sem ex, lobortis vitae condimentum quis, pharetra at nisl. Quisque accumsan risus eu auctor pellentesque. Donec a lectus ullamcorper, tempor dolor non, tristique odio. Quisque velit nisl, malesuada eget porttitor porttitor, scelerisque ut nulla. Phasellus tincidunt justo vel nibh tempus, eu condimentum dui consequat.'
	}
];
export default tours;
